algoritmo "exercicio6"

// 7) Assinalar os comandos de atribuição considerados inválidos:

var
NOME, COR, TESTE, DIA: caracter
SOMA, NUM: inteiro
Salario: real
X: lógico

inicio
a. ( ) NOME <- “5”
b. ( ) SOMA <- NUM + 2 * X
c. ( ) TESTE <- SOMA
d. ( ) NUM <- SOMA
e. ( ) COR <- "PRETO"
f. ( ) X <- X + 1
g. (X) NUM <- "*ABC*"
h. ( ) DIA <- "seGUNDA"
i. (X) SOMA + 2 <- NUM
j. (X) X <- (NOME = COR)
k. ( ) salário <- 5.000
l. ( ) salário <- 150
m. (X) salário <- “insuficiente”

fimalgoritmo
