algoritmo "exercicio4"

var
a, u: inteiro
inicio
//5) Classifique os conteúdo das variáveis abaixo de acordo com seu tipo, assinalando com N
//os dados numéricos, com L os lógicos, com C os literais.

// (C) 0              (C) "abc"         (C) "João"
// (C) 5.7            (C) 1012          ( L) FALSO
// (C) -49            (C) +342          (C) 569
// (C) "Lucas"        (L) "VERDADEIRO"  (C) 0.00001
// (L) VERDADEIRO     (C) -545          (C) " 444 "
fimalgoritmo
