algoritmo "semnome"

var
numero: inteiro
inicio

escreva("Digite um valor inteiro: ")
leia(numero)
escolha numero
caso 1
   escreva("Número 1")
caso 2
   escreva("Número 2")
caso 3
   escreva("Número 3")

outrocaso
   escreva("Valor inexistente")
fimescolha


// Resumindo
//escolha variavel
//caso _valor_
//     bloco
//caso _valor2_
//     bloco
//caso _valor3_
//     bloco
//.
//.
//.
//outrocaso
//     bloco
//fimescolha

fimalgoritmo
