//Subrotinas: São blocos de códigos que se repetem, porém, escrevo apenas uma vez esse bloco e posso usar quado quiser
//inclusive em outros programas

// Procedimentos: não tem retorno
algoritmo "semnome"

var

procedimento soma(a, b: inteiro)
inicio
escreva(a + b)

fimprocedimento

// Resumindo
//procedimento nome-do-procedimento(parametros: tipo)
//var(opcional)
//inicio
//      comandos
//fimprocedimento

inicio

// Chamando o procedimento
soma(12, 8)
fimalgoritmo
