algoritmo "semnome"
var
nome, nome2: caractere

inicio
// Retorna um número inteiro com ASCII
escreval(asc("a"))

// Retorna um caractere utilizando número
escreval(carac(97))

// Comprimento da string
nome <- "James"
escreval(compr(nome))

// Retorna uma string parcial
nome2 <- copia(nome, 1, 3)
escreval(nome2)

// string maiúscula
escreval(maiusc(nome))

//string minuscula
escreval(minusc(nome))
fimalgoritmo
