// Loop: valores que se repetem
algoritmo "Nome do Programa"

var
i: inteiro
inicio
i <- 1
enquanto i <= 10 faca
   escreva(i)
   i <- i + 1
fimenquanto


// incremento: adição de um valor
// decremento: subtração de um valor

// resumindo
// o enquanto realiza o teste lógico no início do programa
//enquanto condicao verdadeirfa faca
//   bloco de comandos
//   incremento/decremento
//fimenquanto
fimalgoritmo
