algoritmo "tabela_verdade"
var



inicio

// Tabela Verdade E
escreval(Verdadeiro e Verdadeiro)
escreval(Verdadeiro e Falso)
escreval(Falso e Verdadeiro)
escreval(Falso e Falso)
escreval()

// Tabela Verdade OU
escreval(Verdadeiro OU Verdadeiro)
escreval(Verdadeiro OU Falso)
escreval(Falso OU Verdadeiro)
escreval(Falso OU Falso)
escreval()

// Tabela Verdade Nao
escreval(Nao verdadeiro)
escreval(Nao Falso)
fimalgoritmo
